"""One-off offline script: generates starter-prompt chips for the frontend
from the corpus, using a single forced-tool-use Claude call so the output is
reliably structured (same convention as llm/assess.py's forced tool use --
this script's output is machine-parsed and written to a file, not read by a
human, which is this project's established criterion for forcing tool use
over free text). Run manually whenever the corpus changes -- not called at
runtime, not a backend endpoint.

Usage: uv run python scripts/generate_starter_prompts.py
"""

import json
from pathlib import Path

from sententia.config import ANTHROPIC_MODEL_ASSESS
from sententia.llm.client import get_client
from sententia.retrieval.corpus import load_corpus

CORPUS_DIR = Path(__file__).resolve().parents[2] / "corpus"
OUTPUT_PATH = Path(__file__).resolve().parents[2] / "frontend" / "lib" / "starter-prompts.ts"

_STARTER_PROMPTS_TOOL = {
    "name": "record_starter_prompts",
    "description": (
        "Record a short list of example legal research questions that this "
        "corpus can confidently answer, for use as clickable starter chips "
        "in a chat UI."
    ),
    "strict": True,
    "input_schema": {
        "type": "object",
        "properties": {
            "prompts": {
                "type": "array",
                "description": "3-6 example starter questions.",
                "items": {"type": "string"},
            },
        },
        "required": ["prompts"],
        "additionalProperties": False,
    },
}


def _summarize_corpus() -> str:
    docs = load_corpus(CORPUS_DIR)
    return "\n".join(f"- ({doc.kind}) {doc.citation} -- topic: {doc.topic}" for doc in docs)


def _build_prompt(corpus_summary: str) -> str:
    return (
        "You are choosing example starter questions for a legal research "
        "assistant's chat UI. The assistant answers ONLY from the fixed "
        "corpus of NSW residential tenancy legislation and NCAT case law "
        "summarized below -- it has no other legal knowledge. Choose ~5 "
        "questions a real user might plausibly ask that this corpus can "
        "confidently answer (i.e. the topics below directly cover the "
        "question), phrased naturally, not as legal citations.\n\n"
        f"CORPUS CONTENTS:\n{corpus_summary}\n\n"
        "Call record_starter_prompts with your choices."
    )


def main() -> None:
    client = get_client()
    response = client.messages.create(
        model=ANTHROPIC_MODEL_ASSESS,
        max_tokens=512,
        tools=[_STARTER_PROMPTS_TOOL],
        tool_choice={"type": "tool", "name": "record_starter_prompts"},
        messages=[{"role": "user", "content": _build_prompt(_summarize_corpus())}],
    )
    tool_use_block = next(b for b in response.content if b.type == "tool_use")
    prompts: list[str] = list(tool_use_block.input["prompts"])

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ts_content = (
        "// AUTO-GENERATED by backend/scripts/generate_starter_prompts.py.\n"
        "// Regenerate (do not edit by hand) if the corpus changes.\n"
        f"export const STARTER_PROMPTS: string[] = {json.dumps(prompts, indent=2)};\n"
    )
    OUTPUT_PATH.write_text(ts_content)
    print(f"Wrote {len(prompts)} starter prompts to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
