// AUTO-GENERATED by backend/scripts/generate_starter_prompts.py.
// Regenerate (do not edit by hand) if the corpus changes.
export const STARTER_PROMPTS: string[] = [
  "How much notice does a landlord need to give before increasing my rent?",
  "Can I get my bond back if the landlord claims deductions for wear and tear?",
  "What can I do if my landlord won't fix a broken toilet or other serious repair problem?",
  "Can a landlord evict me just because they want to renovate the property?",
  "What's considered 'fair wear and tear' in a rental property?"
];
